baseURL = 'https://webdev.evlis.org/'
languageCode = 'en-us'
title = 'Eclectic Peddler Atelier'
theme = 'sky'
disqusShortname = "your_disqus_shortname"
contentDir = "./content"

[menu]
  [[menu.header]]
    name = "portfolio"
    weight = 0
    url = "/portfolio"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"


[params]
  GithubID = "Ifiht"
  StackOverflowID = "12027622/ifiht"
  EthereumID = "ifiht.eth"
  Name = "Eclectic Peddler Atelier, LLC."
  Email = "eclecticpeddlerllc@gmail.comDELETETHISTOPROVEYOUAREHUMAN"
  tagline = "Full Stack Developer"
  about = ""
  ProfilePicture = "/profile.png"
