baseURL = 'https://webdev.evlis.org/'
languageCode = 'en-us'
title = 'Eclectic Peddler Atelier'
theme = 'bloodsky'
contentDir = "./content"

[menu]
  [[menu.header]]
    name = "portfolio"
    weight = 2
    url = "/portfolio"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"
  [[menu.header]]
    name = "services"
    weight = 1
    url = "/pricing"
  [[menu.header]]
    name = "blog"
    weight = 3
    url = "/blog"

[params]
  GithubID = "Ifiht"
  StackOverflowID = "12027622/ifiht"
  EthereumID = "evlis.eth"
  Name = "Eclectic Peddler Atelier, LLC."
  Email = "eclecticpeddlerllc@gmail.comDELETETHISTOPROVEYOUAREHUMAN"
  tagline = "Full Stack Developer"
  about = ""
  description = "Personal blog and business site of the eclectic peddler."
  ProfilePicture = "/profile.png"

[markup.goldmark.renderer]
  unsafe=true
